In [1]:
import numpy as np

In [2]:
myarr = np.array([1,4,1452512455,6], np.int32) 
# In this way we can control memory

In [3]:
myarr

array([         1,          4, 1452512455,          6], dtype=int32)

In [4]:
print(myarr.shape)
print(myarr.dtype)

(4,)
int32


In [11]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
x.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
print(x.sum(axis = 0))
print(x.sum(axis = 1))

[12 15 18]
[ 6 15 24]


In [16]:
x.T # It will transpose the array.

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [20]:
for i in x.flat:
    print(i)

# .flat is an ittrator and it let's us to iterate through the contents of 
# out array.

1
2
3
4
5
6
7
8
9


In [22]:
x.nbytes # It gives the space taken by out array.

72