In [1]:
import numpy as np 
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,3,5],[15,61,6],[16,4,12]])
C = A+B
print(C)

[[ 2  5  8]
 [19 66 12]
 [23 12 21]]


In [3]:
D = A-B
print(D)

[[  0  -1  -2]
 [-11 -56   0]
 [ -9   4  -3]]


In [4]:
E = A*B
print(E)

[[  1   6  15]
 [ 60 305  36]
 [112  32 108]]


In [5]:
F = A/B
print(F)

[[1.         0.66666667 0.6       ]
 [0.26666667 0.08196721 1.        ]
 [0.4375     2.         0.75      ]]


In [6]:
X = np.array([1,3,35])
G = A@X
print(G)

[112 229 346]


In [7]:
b = 12
H = A*b
print(H)

[[ 12  24  36]
 [ 48  60  72]
 [ 84  96 108]]
