In [6]:
import numpy as np
A = np.array([[1,4,67],[2,1,61],[6,1,7]])
lower = np.tril(A)
print(lower)
upper = np.triu(A)
print(upper)

[[1 0 0]
 [2 1 0]
 [6 1 7]]
[[ 1  4 67]
 [ 0  1 61]
 [ 0  0  7]]


In [8]:
Diag = np.diag(A)
diag = np.diag(Diag)
print(diag)

[[1 0 0]
 [0 1 0]
 [0 0 7]]


In [9]:
I = np.identity(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
