## Triangular.

In [1]:
import numpy as np
def lower(A):
    a = A.shape[0]-1
    for i in range(a+1):
        for j in range(a+1):
            if i>j:
                A[j,i] = 0
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
lower(A)
print(A)

[[1 0 0]
 [4 5 0]
 [7 8 9]]


In [2]:
def upper(A):
    a = A.shape[0]-1
    for i in range(a+1):
        for j in range(a+1):
            if j>i:
                A[j,i] = 0
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
upper(A)
print(A)

[[1 2 3]
 [0 5 6]
 [0 0 9]]


## Diagonal

In [3]:
def diag(A):
    a = A.shape[0]-1
    for i in range(a+1):
        for j in range(a+1):
            if i != j:
                A[i,j] = 0
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
diag(A)
print(A)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


## Identity

In [4]:
def identity(a):
    A = np.arange(a*a).reshape(a,a)
    for i in range(a):
        for j in range(a):
            if i == j:
                A[i,j] = 1
            else:
                A[i,j] = 0
    print(A)
identity(4)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
