In [2]:
import numpy as np
A = np.array([[1,54,6],[16,61,14]])
print(A)
A = A.T
print(A)

[[ 1 54  6]
 [16 61 14]]
[[ 1 16]
 [54 61]
 [ 6 14]]


In [7]:
B = np.array([[4,1],[15,76]])
print(B)
C = np.linalg.inv(B)
print(C)
I = C.dot(B)
print(I)

[[ 4  1]
 [15 76]]
[[ 0.26297578 -0.00346021]
 [-0.05190311  0.01384083]]
[[ 1.00000000e+00 -1.66533454e-16]
 [ 0.00000000e+00  1.00000000e+00]]


In [10]:
D = np.arange(16).reshape(4,4)
print(D)
E = np.trace(D)
print(E)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
30


In [12]:
F = np.arange(25).reshape(5,5)
print(F)
f = np.linalg.det(F)
print(f)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
0.0


In [14]:
G = np.array([3,51,1])
g = np.linalg.matrix_rank(G)
print(g)

1


In [15]:
H = np.arange(25).reshape(5,5)
h = np.linalg.matrix_rank(H)
print(h)

2
