## Transpose

In [12]:
import numpy as np
def trans(A,rows,cols):
    B = np.zeros((cols,rows))
    for i in range(rows):
        for j in range(cols):
            B[j,i] = A[i,j]
    print(B)
A = np.array([[1,2],[3,4],[5,6]])
print(A)
trans(A,3,2)

[[1 2]
 [3 4]
 [5 6]]
[[1. 3. 5.]
 [2. 4. 6.]]


## Trace

In [14]:
def trace(A):
    a = 0
    b = A.shape[0]
    for i in range(b):
        a = a+A[i,i]
    print(a)
A = np.arange(25).reshape(5,5)
trace(A)

60
