In [10]:
import numpy as np
import scipy
A = np.array([[1,0,0,3,0,2],
             [2,0,0,0,5,0],
             [0,0,2,0,4,0]])
print(A)
S = scipy.sparse.csr_matrix(A)
print(S)
sparcity = 1.0 - np.count_nonzero(A)/A.size
print(sparcity)

[[1 0 0 3 0 2]
 [2 0 0 0 5 0]
 [0 0 2 0 4 0]]
  (0, 0)	1
  (0, 3)	3
  (0, 5)	2
  (1, 0)	2
  (1, 4)	5
  (2, 2)	2
  (2, 4)	4
0.6111111111111112
