In [10]:
import numpy as np
from scipy import sparse
A = np.array([[1,0,0,0,2,0],
             [5,0,0,0,0,2],
             [0,0,3,0,0,0]])
print(A)
A_csr = sparse.csr_matrix(A)
print(A_csr)

[[1 0 0 0 2 0]
 [5 0 0 0 0 2]
 [0 0 3 0 0 0]]
  (0, 0)	1
  (0, 4)	2
  (1, 0)	5
  (1, 5)	2
  (2, 2)	3


In [11]:
print(A_csr.toarray())


[[1 0 0 0 2 0]
 [5 0 0 0 0 2]
 [0 0 3 0 0 0]]
