## Addition

In [1]:
import numpy as np
def addition(A,B):
    C = np.zeros(A.shape)
    a = A.shape[0]
    b = A.shape[1]
    c = A.shape[2]
    for i in range(a):
        for j in range(b):
            for k in range(c):
                C[i,j,k] = A[i,j,k] + B[i,j,k]
    print(C)
A = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
B = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
addition(A,B)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]]

 [[22. 24. 26.]
  [28. 30. 32.]
  [34. 36. 38.]]

 [[42. 44. 46.]
  [48. 50. 52.]
  [54. 56. 58.]]]


## Subtraction

In [2]:
def subtraction(A,B):
    C = np.zeros(A.shape)
    a = A.shape[0]
    b = A.shape[1]
    c = A.shape[2]
    for i in range(a):
        for j in range(b):
            for k in range(c):
                C[i,j,k] = A[i,j,k] - B[i,j,k]
    print(C)
A = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
B = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
subtraction(A,B)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


## Multiplication

In [3]:
def multiplication(A,B):
    C = np.zeros(A.shape)
    a = A.shape[0]
    b = A.shape[1]
    c = A.shape[2]
    for i in range(a):
        for j in range(b):
            for k in range(c):
                C[i,j,k] = A[i,j,k] * B[i,j,k]
    print(C)
A = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
B = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
multiplication(A,B)

[[[  1.   4.   9.]
  [ 16.  25.  36.]
  [ 49.  64.  81.]]

 [[121. 144. 169.]
  [196. 225. 256.]
  [289. 324. 361.]]

 [[441. 484. 529.]
  [576. 625. 676.]
  [729. 784. 841.]]]


## Division

In [4]:
def division(A,B):
    C = np.zeros(A.shape)
    a = A.shape[0]
    b = A.shape[1]
    c = A.shape[2]
    for i in range(a):
        for j in range(b):
            for k in range(c):
                C[i,j,k] = A[i,j,k] / B[i,j,k]
    print(C)
A = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
B = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
division(A,B)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
