# SVD and reconstruction

In [9]:
import numpy as np
import scipy as sp
A = np.array([[1,4,4,3,62,61,671],[13,6,71,71,1,2,72]])
U,S,VT = sp.linalg.svd(A)
sigma = np.zeros([A.shape[0],A.shape[1]])
sigma[:A.sshape[0],:A.shape[0]] = np.diag(S)
B = U.dot(sigma.dot(VT))
print(B)

[[  1.   4.   4.   3.  62.  61. 671.]
 [ 13.   6.  71.  71.   1.   2.  72.]]


# Pseudoinverse

In [11]:
d = 1.0/S
D = np.zeros(A.shape)
D[:A.shape[0],:A.shape[0]] = np.diag(d)
E = VT.T.dot(D.T).dot(U.T)
print(E)

[[-1.32838935e-04  1.26086153e-03]
 [-4.96134456e-05  5.44878989e-04]
 [-7.30336252e-04  6.90154991e-03]
 [-7.33641878e-04  6.91202257e-03]
 [ 1.94476180e-04 -5.51509893e-04]
 [ 1.80697895e-04 -4.43242297e-04]
 [ 1.46404392e-03  1.40815927e-05]]


# Dimensionality reduction

In [17]:
n_elements = 3
sigma = sigma[:,:n_elements]
VT = VT[:,:n_elements]
B = U.dot(sigma.dot(VT.T))
T = U.dot(sigma)
print(T)

[[676.55616139 -10.94351367   0.        ]
 [ 74.08645938  99.93596218   0.        ]]


# Data reduction via svd in scikit learn

In [19]:
from sklearn.decomposition import TruncatedSVD
svd = TruncatedSVD(n_components = 3)
svd.fit(A)
result = svd.transform(A)
print(result)

[[676.55616139 -10.94351367]
 [ 74.08645938  99.93596218]]
