In [16]:
import numpy as np 
A = np.array([[11,34,22],[14,15,51],[56,1,61]])
M = np.mean(A.T, axis = 1)
C = A-M
V = np.cov(C)
values, vectors = np.linalg.eig(V)
P = vectors.dot(C)
print(P)

[[ 16.63993502 -19.86431435  26.46108397]
 [-30.1256452   10.72002099  -8.23842008]
 [ -9.03095031   6.25754201  -7.25300878]]


In [15]:
from sklearn.decomposition import PCA
pca = PCA(2)
pca.fit(A)
D = pca.transform(A)
D

array([[-31.63846766,  -8.32043187],
       [ -4.74300424,  13.76200566],
       [ 36.38147189,  -5.44157378]])