In [1]:
import numpy as np 
a = np.array([3,5,1])
b = np.array([6,12,9])
x = 5

In [2]:
c = a+b
print(c)

[ 9 17 10]


In [3]:
d = a-b
print(d)

[-3 -7 -8]


In [4]:
e = a*b
print(e)

[18 60  9]


In [5]:
f = a/b
print(f)

[0.5        0.41666667 0.11111111]


In [6]:
g = a.dot(b)
g

87

In [7]:
h = x*a
i = x*b
print(h)
print(i)

[15 25  5]
[30 60 45]
