In [9]:
import numpy as np 
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[2])
print(a[5])
a[5] = 10
print(a)

3
6
[ 1  2  3  4  5 10  7  8  9]


In [11]:
print(a[1:5])
print(a[-3:])

[2 3 4 5]
[7 8 9]


In [12]:
a = a.reshape((3,3))
print(a)

[[ 1  2  3]
 [ 4  5 10]
 [ 7  8  9]]
