In [7]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([3,4,5])
c = a+b
c

array([[ 4,  6,  8],
       [ 7,  9, 11],
       [10, 12, 14]])

In [8]:
a = np.array([11,22,33])
b = 10
c = a+b
c

array([21, 32, 43])

In [12]:
a = np.arange(27).reshape(3,3,3)
print(a)
b = 2
c = a*b
c

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]],

       [[18, 20, 22],
        [24, 26, 28],
        [30, 32, 34]],

       [[36, 38, 40],
        [42, 44, 46],
        [48, 50, 52]]])