In [8]:
import numpy as np 
a = np.arange(21)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [9]:
b = np.arange(16).reshape(4,4)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [13]:
c = np.zeros((4,3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
d = np.ones((2,2))
print(d)

[[1. 1.]
 [1. 1.]]


In [15]:
e = np.empty((2,3))
print(e)