In [6]:
import numpy as np
a = np.array([[3,2,5],[13,5,51]])
b = np.array([[12,3,4],[3,1,4]])
c = np.vstack((a,b))
print(c)

[[ 3  2  5]
 [13  5 51]
 [12  3  4]
 [ 3  1  4]]


In [7]:
d = np.array([[3,45,6],[54,25,6]])
e = np.array([[35,52,6],[4,3,7]])
f = np.hstack((d,e))
print(f)

[[ 3 45  6 35 52  6]
 [54 25  6  4  3  7]]


In [10]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]
