# Q.1

In [5]:
from random import seed, randint
import numpy as np
seed(1)
python = [randint(1,10),randint(1,10),randint(1,10)]
numpy1 = np.random.randint(1,10,3)
numpy2 = np.random.randint(1,10,3)
print(python)
print(numpy1)
print(numpy2)

[3, 10, 2]
[5 5 5]
[5 6 1]


As we can see in the result, seeding the numpy random generator does not effect the numpy random generator as the result of numpy's random generator are still different.

# Q.2

In [10]:
import random
A = random.random()
B = random.randint(1,39)
C = []
for i in range(15):
    value = random.gauss(0,1)
    C.append(value)
D = random.choice(C)
E = random.sample(C,4)
print(A)
print(B)
print(C)
print(D)
print(E)

0.6592148136198245
39
[0.3890044161673872, 0.6976644344684755, -1.1513987342189846, 0.43909507113500706, 1.240123870623568, -0.028485624983674466, 1.8957484626184458, -1.8120923658246146, 0.10314817894159017, -1.126780495468637, -1.0770869202964841, -0.2843102001962331, -0.6041964940486672, -0.39628787527150033, -0.9764853646109403]
-1.0770869202964841
[0.43909507113500706, -1.0770869202964841, 0.10314817894159017, -0.9764853646109403]
None


In [11]:
import numpy.random as random
A = random.rand(15)
B = random.randint(1,15,22)
C = random.randn(5)
print(A)
print(B)
print(C)

[0.62133168 0.24058666 0.69918732 0.62670246 0.01339928 0.82721607
 0.60172404 0.05649186 0.07262294 0.2698969  0.97410491 0.61722756
 0.55551481 0.85087852 0.87698148]
[ 5  4 12 14  4  5  6  9  3 11 10 14 11  5  7  2  9  4 11 12  3  3]
[ 1.03914122 -0.56993111 -0.25295755 -1.7194777  -1.0463206 ]
