# Q.1

In [1]:
from random import seed, randint
import numpy as np
seed(1)
python = [randint(1,10),randint(1,10),randint(1,10)]
numpy1 = np.random.randint(1,10,3)
numpy2 = np.random.randint(1,10,3)
print(python)
print(numpy1)
print(numpy2)

[3, 10, 2]
[9 3 6]
[1 2 9]


As we can see in the result, seeding the numpy random generator does not effect the numpy random generator as the result of numpy's random generator are still different.

# Q.2

In [2]:
import random
A = random.random()
B = random.randint(1,39)
C = []
for i in range(15):
    value = random.gauss(0,1)
    C.append(value)
D = random.choice(C)
E = random.sample(C,4)
print(A)
print(B)
print(C)
print(D)
print(E)

0.2550690257394217
32
[0.07781283712174002, -1.1279150330037588, -0.4993247889966073, 0.47117407734163236, -2.1094507236670066, 0.1612617729414316, -1.052647335280873, 0.8729577043031487, 0.16600323468964862, -1.5338835753205629, -0.18429135176443584, 1.7897653740315347, -0.39030040197713534, -0.25167836943777205, -0.08735515600559883]
-0.18429135176443584
[0.16600323468964862, 0.07781283712174002, -1.052647335280873, -0.18429135176443584]


In [3]:
import numpy.random as random
A = random.rand(15)
B = random.randint(1,15,22)
C = random.randn(5)
print(A)
print(B)
print(C)

[0.80441007 0.82324745 0.04756261 0.44486124 0.13534503 0.30219109
 0.27995354 0.58032213 0.19099328 0.47261564 0.52326063 0.54153565
 0.07016453 0.51910818 0.6269361 ]
[11 13  8  3  7 13  8 14 13  3  5  8  7  6  6  4  4 13  3  5  6 10]
[ 0.85039577  0.60325935 -0.21963531  1.74985819  0.60294217]
